<a href="https://colab.research.google.com/github/JaswanthJavangula/ML_Practise/blob/main/1ML%20JAshu%20/SVM/svm_prac_SVC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [173]:
# Install dependencies as needed:

import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Loan.csv" # Corrected file path

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS, # Adapter should be the first argument for load_dataset
  "lorenzozoppelletto/financial-risk-for-loan-approval",
  file_path
)
df = df.head(5500)
print("First 5 records:", df.head())

Using Colab cache for faster access to the 'financial-risk-for-loan-approval' dataset.
First 5 records:   ApplicationDate  Age  AnnualIncome  CreditScore EmploymentStatus  \
0      2018-01-01   45         39948          617         Employed
1      2018-01-02   38         39709          628         Employed
2      2018-01-03   47         40724          570         Employed
3      2018-01-04   58         69084          545         Employed
4      2018-01-05   37        103264          594         Employed

  EducationLevel  Experience  LoanAmount  LoanDuration MaritalStatus  ...  \
0         Master          22       13152            48       Married  ...
1      Associate          15       26045            48        Single  ...
2       Bachelor          26       17627            36       Married  ...
3    High School          34       37898            96        Single  ...
4      Associate          17        9184            36       Married  ...

   MonthlyIncome UtilityBillsPaymentHistory  JobTenure  NetWorth  \
0    3329.000000                   0.724972         11    126928
1    3309.083333                   0.935132          3     43609
2    3393.666667                   0.872241          6      5205
3    5757.000000                   0.896155          5     99452
4    8605.333333                   0.941369          5    227019

   BaseInterestRate  InterestRate  MonthlyLoanPayment  TotalDebtToIncomeRatio  \
0          0.199652      0.227590          419.805992                0.181077
1          0.207045      0.201077          794.054238                0.389852
2          0.217627      0.212548          666.406688                0.462157
3          0.300398      0.300911         1047.506980                0.313098
4          0.197184      0.175990          330.179140                0.070210

  LoanApproved  RiskScore
0            0       49.0
1            0       52.0
2            0       52.0
3            0       54.0
4            1       36.0

[5 rows x 36 columns]

In [174]:
import pandas as pd
import numpy as np

In [175]:
df.tail(3)

,ApplicationDate,Age,AnnualIncome,CreditScore,EmploymentStatus,EducationLevel,Experience,LoanAmount,LoanDuration,MaritalStatus,...,MonthlyIncome,UtilityBillsPaymentHistory,JobTenure,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore
5497,2033-01-19,32,21169,556,Employed,Bachelor,9,17247,60,Married,...,1764.083333,0.762538,6,4487,0.244247,0.248825,505.035009,0.573689,0,57.0
5498,2033-01-20,18,53388,585,Unemployed,Associate,0,16237,60,Married,...,4449.000000,0.878342,5,53723,0.228737,0.233177,460.697083,0.213238,0,60.0
5499,2033-01-21,59,25151,572,Employed,High School,37,15511,48,Married,...,2095.916667,0.836795,2,29012,0.224511,0.235542,501.872124,0.346327,0,70.0

In [176]:
df.columns

Index(['ApplicationDate', 'Age', 'AnnualIncome', 'CreditScore',
       'EmploymentStatus', 'EducationLevel', 'Experience', 'LoanAmount',
       'LoanDuration', 'MaritalStatus', 'NumberOfDependents',
       'HomeOwnershipStatus', 'MonthlyDebtPayments',
       'CreditCardUtilizationRate', 'NumberOfOpenCreditLines',
       'NumberOfCreditInquiries', 'DebtToIncomeRatio', 'BankruptcyHistory',
       'LoanPurpose', 'PreviousLoanDefaults', 'PaymentHistory',
       'LengthOfCreditHistory', 'SavingsAccountBalance',
       'CheckingAccountBalance', 'TotalAssets', 'TotalLiabilities',
       'MonthlyIncome', 'UtilityBillsPaymentHistory', 'JobTenure', 'NetWorth',
       'BaseInterestRate', 'InterestRate', 'MonthlyLoanPayment',
       'TotalDebtToIncomeRatio', 'LoanApproved', 'RiskScore'],
      dtype='object')

In [177]:
df["RiskScore"]

0       49.0
1       52.0
2       52.0
3       54.0
4       36.0
        ...
5495    50.0
5496    44.8
5497    57.0
5498    60.0
5499    70.0
Name: RiskScore, Length: 5500, dtype: float64

In [178]:
X = df[[
    "Age",
    "AnnualIncome",
    "CreditScore",
    "LoanAmount",
    "LoanDuration",
    "MonthlyDebtPayments",
    "DebtToIncomeRatio",
    "TotalDebtToIncomeRatio",
    "NetWorth",
    "RiskScore"
]]
y= df["LoanApproved"]
X.head(4)

,Age,AnnualIncome,CreditScore,LoanAmount,LoanDuration,MonthlyDebtPayments,DebtToIncomeRatio,TotalDebtToIncomeRatio,NetWorth,RiskScore
0,45,39948,617,13152,48,183,0.358336,0.181077,126928,49.0
1,38,39709,628,26045,48,496,0.330274,0.389852,43609,52.0
2,47,40724,570,17627,36,902,0.244729,0.462157,5205,52.0
3,58,69084,545,37898,96,755,0.436244,0.313098,99452,54.0

In [179]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=32,stratify=y)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [180]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
svc = SVC()
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)

print("Confusion Matrix :\n", confusion_matrix(y_test, y_pred))
print("Accuracy Score :", accuracy_score(y_test, y_pred))
print("Precision Score :", precision_score(y_test, y_pred))
print("Recall Score :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

Confusion Matrix :
 [[833   1]
 [  3 263]]
Accuracy Score : 0.9963636363636363
Precision Score : 0.9962121212121212
Recall Score : 0.9887218045112782
F1 Score : 0.9924528301886792

In [181]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import GridSearchCV

param_grid = {
    "C" : [0.1,0.001,0.001,1],
    "gamma" : [0.0001,0.1,0.01,"scale"],
    "kernel" : ["poly","linear"]
}

grid = GridSearchCV(SVC(), param_grid, cv= 4, refit= True)
grid.fit(X_train_scaled,y_train)

GridSearchCV(cv=4, estimator=SVC(),
             param_grid={'C': [0.1, 0.001, 0.001, 1],
                         'gamma': [0.0001, 0.1, 0.01, 'scale'],
                         'kernel': ['poly', 'linear']})

In [182]:
grid.best_params_

{'C': 1, 'gamma': 0.0001, 'kernel': 'linear'}

In [183]:
grid.best_estimator_

SVC(C=1, gamma=0.0001, kernel='linear')

In [184]:
grid_prid= grid.predict(X_test_scaled)

print("Confusion Matrix :\n", confusion_matrix(y_test, grid_prid))
print("Accuracy Score :", accuracy_score(y_test, grid_prid))
print("Precision Score :", precision_score(y_test, grid_prid))
print("Recall Score :", recall_score(y_test, grid_prid))
print("F1 Score :", f1_score(y_test, grid_prid))

Confusion Matrix :
 [[833   1]
 [  2 264]]
Accuracy Score : 0.9972727272727273
Precision Score : 0.9962264150943396
Recall Score : 0.9924812030075187
F1 Score : 0.9943502824858758

### Adding Categorical Features from here

In [185]:
numeric_features = [
    "Age",
    "AnnualIncome",
    "CreditScore",
    "LoanAmount",
    "LoanDuration",
    "MonthlyDebtPayments",
    "DebtToIncomeRatio",
    "TotalDebtToIncomeRatio",
    "NetWorth",
    "RiskScore"
]
categorical_features = [
    "EmploymentStatus",
    "EducationLevel",
    "MaritalStatus",
    "HomeOwnershipStatus",
    "LoanPurpose"
]

In [186]:
X_full = df[ numeric_features + categorical_features]
y_full = df["LoanApproved"]

In [187]:
df_full = pd.concat([X_full,y_full],axis=1)
df_full.head(3)

,Age,AnnualIncome,CreditScore,LoanAmount,LoanDuration,MonthlyDebtPayments,DebtToIncomeRatio,TotalDebtToIncomeRatio,NetWorth,RiskScore,EmploymentStatus,EducationLevel,MaritalStatus,HomeOwnershipStatus,LoanPurpose,LoanApproved
0,45,39948,617,13152,48,183,0.358336,0.181077,126928,49.0,Employed,Master,Married,Own,Home,0
1,38,39709,628,26045,48,496,0.330274,0.389852,43609,52.0,Employed,Associate,Single,Mortgage,Debt Consolidation,0
2,47,40724,570,17627,36,902,0.244729,0.462157,5205,52.0,Employed,Bachelor,Married,Rent,Education,0

In [188]:
X_train, X_test, y_train, y_test = train_test_split(X_full, y_full, test_size=0.2, random_state=32,stratify=y_full)

In [189]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ("onehot", OneHotEncoder(drop= "first"),categorical_features)],
        remainder= "passthrough")

X_train_encoded = ct.fit_transform(X_train)
X_test_encoded = ct.transform(X_test)

In [190]:
feature_names = ct.get_feature_names_out()
X_train_encoded_df = pd.DataFrame(X_train_encoded, columns=feature_names)
display(X_train_encoded_df.head())

,onehot__EmploymentStatus_Self-Employed,onehot__EmploymentStatus_Unemployed,onehot__EducationLevel_Bachelor,onehot__EducationLevel_Doctorate,onehot__EducationLevel_High School,onehot__EducationLevel_Master,onehot__MaritalStatus_Married,onehot__MaritalStatus_Single,onehot__MaritalStatus_Widowed,onehot__HomeOwnershipStatus_Other,...,remainder__Age,remainder__AnnualIncome,remainder__CreditScore,remainder__LoanAmount,remainder__LoanDuration,remainder__MonthlyDebtPayments,remainder__DebtToIncomeRatio,remainder__TotalDebtToIncomeRatio,remainder__NetWorth,remainder__RiskScore
0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,38.0,62891.0,538.0,15867.0,60.0,1309.0,0.433431,0.334081,273416.0,41.6
1,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,56.0,37093.0,626.0,10742.0,36.0,407.0,0.157997,0.259373,41270.0,48.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,24.0,141563.0,541.0,8322.0,72.0,574.0,0.357659,0.067602,170699.0,40.8
3,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,48.0,42140.0,624.0,23545.0,96.0,447.0,0.020165,0.294665,106929.0,47.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,18.0,22191.0,556.0,21199.0,36.0,163.0,0.222167,0.534713,9526.0,59.0

In [201]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)
# print(X_train_encoded)

In [192]:
scaler1 = StandardScaler()
X_train_full_scaled = scaler1.fit_transform(X_train_encoded)
X_test_full_scaled = scaler1.transform(X_test_encoded)

In [193]:
svc1 = SVC()
svc1.fit(X_train_full_scaled,y_train)
y_pred_full = svc1.predict(X_test_full_scaled)

print("Confusion Matrix :\n", confusion_matrix(y_test, y_pred_full))
print("Accuracy Score :", accuracy_score(y_test, y_pred_full))
print("Precision Score :", precision_score(y_test, y_pred_full))
print("Recall Score :", recall_score(y_test, y_pred_full))

Confusion Matrix :
 [[833   1]
 [  2 264]]
Accuracy Score : 0.9972727272727273
Precision Score : 0.9962264150943396
Recall Score : 0.9924812030075187

In [198]:

param_grid1 = {
    "C" : [0.1,0.001,1,10],
    "gamma" : [0.0001,0.1,0.01,"scale"],
    "kernel" : ["poly","linear","rbf"]
}
grid_full = GridSearchCV(SVC(), param_grid1, cv= 4, refit= True)
grid_full.fit(X_train_full_scaled,y_train)
grid_full_pred= grid_full.predict(X_test_full_scaled)
print("Confusion Matrix :\n", confusion_matrix(y_test, grid_full_pred))
print("Accuracy Score :", accuracy_score(y_test, grid_full_pred))
print("Precision Score :", precision_score(y_test, grid_full_pred))
print("Recall Score :", recall_score(y_test, grid_full_pred))
print("F1 Score :", f1_score(y_test, grid_full_pred))

Confusion Matrix :
 [[834   0]
 [  2 264]]
Accuracy Score : 0.9981818181818182
Precision Score : 1.0
Recall Score : 0.9924812030075187
F1 Score : 0.9962264150943396

In [199]:
grid_full.best_params_

{'C': 1, 'gamma': 0.01, 'kernel': 'rbf'}

### comparing with Logistic Regression

In [200]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver="liblinear")
lr.fit(X_train_full_scaled,y_train)
lr_pred = lr.predict(X_test_full_scaled)
print("Confusion Matrix :\n", confusion_matrix(y_test, lr_pred))
print("Accuracy Score :", accuracy_score(y_test, lr_pred))
print("Precision Score :", precision_score(y_test, lr_pred))
print("Recall Score :", recall_score(y_test, lr_pred))
print("F1 Score :", f1_score(y_test, lr_pred))

Confusion Matrix :
 [[833   1]
 [  2 264]]
Accuracy Score : 0.9972727272727273
Precision Score : 0.9962264150943396
Recall Score : 0.9924812030075187
F1 Score : 0.9943502824858758