<a href="https://colab.research.google.com/github/JaswanthJavangula/ML_Practise/blob/main/1ML%20JAshu/RandomForest%5BCLASS%26REGRE%5D/prac_RFR_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "train.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "jaswanthjavangula/housing-regression",
  file_path,
)

print("First 5 records:", df.head())

/tmp/ipykernel_11614/662268775.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'housing-regression' dataset.
First 5 records:    Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg
1   2          20       RL         80.0     9600   Pave   NaN      Reg
2   3          60       RL         68.0    11250   Pave   NaN      IR1
3   4          70       RL         60.0     9550   Pave   NaN      IR1
4   5          60       RL         84.0    14260   Pave   NaN      IR1

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12

  YrSold  SaleType  SaleCondition  SalePrice
0   2008        WD         Normal     208500
1   2007        WD         Normal     181500
2   2008        WD         Normal     223500
3   2006        WD        Abnorml     140000
4   2008        WD         Normal     250000

[5 rows x 81 columns]

In [71]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [72]:
df = pd.DataFrame(df)
df.drop("Id",axis=1,inplace=True)
df.head(3)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500

In [73]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [74]:
df.isnull().sum().sort_values(ascending=False).head(21)

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
MasVnrType       872
FireplaceQu      690
LotFrontage      259
GarageQual        81
GarageType        81
GarageFinish      81
GarageCond        81
GarageYrBlt       81
BsmtExposure      38
BsmtFinType2      38
BsmtQual          37
BsmtFinType1      37
BsmtCond          37
MasVnrArea         8
Electrical         1
BldgType           0
Neighborhood       0
dtype: int64

In [75]:
y = df["SalePrice"]
X = df.drop("SalePrice",axis=1)

In [76]:
# numeric_col = [i for i in df.columns if df[i].dtypes != "O"]
# categorical_col = [i for i in df.columns if i not in numeric_col]

In [77]:
# print("Numerical Cols:",len(numeric_col))
# print("Categorical Cols:",len(categorical_col))

In [78]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=22)

num_features = [i for i in X.columns if X[i].dtypes != "O"]
cat_features = [i for i in X.columns if i not in num_features]

In [79]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, root_mean_squared_error, mean_absolute_error

numeric_TRANSFORMER = Pipeline(
    steps = [
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
        )

cat_transformer = Pipeline(
    steps = [
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("oneHot", OneHotEncoder(handle_unknown = "ignore"))
    ]
)

preprocess = ColumnTransformer(
    transformers=[
    ("cat_trans", cat_transformer, cat_features),
    ("num_tran", numeric_TRANSFORMER, num_features)
])

rf = RandomForestRegressor(max_depth=6, n_estimators=60,random_state=42)

In [85]:
rf_pipeline = Pipeline(
    steps= [
        ("preprocessing", preprocess),
        ("model", rf)
    ]
)

rf_pipeline.fit(X_train, y_train)

y_train_pred = rf_pipeline.predict(X_train)
y_val_pred = rf_pipeline.predict(X_val)

lr_pipeline = Pipeline(
    steps= [
        ("preprocessing", preprocess),
        ("model", LinearRegression())
    ]
)

In [81]:
# train_eval(y_train, y_train_pred)

# val_eval(y_val, y_val_pred)

In [82]:
def eval_met (actual, pred):
  rmse = np.sqrt(mean_squared_error(actual, pred))
  mae = mean_absolute_error(actual, pred)
  r2 = r2_score(actual, pred)
  return rmse, mae, r2

In [87]:
models ={
    "Random Forest Pipeline" :rf_pipeline,
    "Linear Regression" :lr_pipeline
}

for i in range(len(list(models))):
  model = list(models.values())[i]
  model.fit(X_train,y_train)

  y_train_pred1 = model.predict(X_train)
  y_val_pred1 = model.predict(X_val)

  print(list(models.keys())[i])

  train_rmse, train_mae , train_r2 = eval_met(y_train,y_train_pred1)
  val_rmse, val_mae,val_r2 = eval_met(y_val,y_val_pred1)

  print("Train RMSE:",train_rmse)
  print("Train MAE:",train_mae)
  print("Train R2:",train_r2)
  print("-"*50)
  print("Val RMSE:",val_rmse)
  print("Val MAE:",val_mae)
  print("Val R2:",val_r2)
  print("*"*50)

Random Forest Pipeline
Train RMSE: 19167.39220359247
Train MAE: 13669.964132242229
Train R2: 0.9428335041135125
--------------------------------------------------
Val RMSE: 31341.796957140246
Val MAE: 19657.027959555264
Val R2: 0.8379565672244821
**************************************************
Linear Regression
Train RMSE: 18491.79283509791
Train MAE: 12725.130024294876
Train R2: 0.9467924144495311
--------------------------------------------------
Val RMSE: 45862.7018081543
Val MAE: 20181.96156816694
Val R2: 0.6530212158819785
**************************************************