<a href="https://colab.research.google.com/github/JaswanthJavangula/ML_Practise/blob/main/1ML%20JAshu/SVM/support_vector_regression_implement_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
df =sns.load_dataset("tips")

df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [3]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [4]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [5]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [6]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [7]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [8]:
X = df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
X
y = df[["total_bill"]]
y

     total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=10)

In [10]:
# Label encoding convertinf the binary cat
# into numbers
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

X_train["sex"]= le1.fit_transform(X_train["sex"])
X_train["smoker"]= le2.fit_transform(X_train["smoker"])
X_train["time"]= le3.fit_transform(X_train["time"])

In [11]:
X_train.head(3)

     tip  sex  smoker  day  time  size
58  1.76    1       1  Sat     0     2
1   1.66    1       0  Sun     0     3
2   3.50    1       0  Sun     0     3

In [12]:
X_test["sex"]= le1.transform(X_test["sex"])
X_test["smoker"]= le2.transform(X_test["smoker"])
X_test["time"]= le3.transform(X_test["time"])
X_test.head(3)

      tip  sex  smoker  day  time  size
162  2.00    0       0  Sun     0     3
60   3.21    1       1  Sat     0     2
61   2.00    1       1  Sat     0     2

In [13]:
# one hot encoder with column transformer

ct = ColumnTransformer(transformers=
 [("onehot", OneHotEncoder(drop="first"),
   [3])],remainder="passthrough")

In [14]:
import sys
import numpy as np
np.set_printoptions(threshold= sys.maxsize)
X_train= ct.fit_transform(X_train)
X_test= ct.transform(X_test)

In [15]:
svr = SVR()
svr.fit(X_train, y_train)
ypred= svr.predict(X_test)
print("r2 score", r2_score(y_test, ypred))
print("mae", mean_absolute_error(y_test, ypred))

r2 score 0.46028114561159283
mae 4.1486423210190235

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

### hyperparameter tuning

In [16]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import GridSearchCV
param_grid = {
    "C" : [0.01, 0.1, 1, 10],
    "gamma" : [1,0.1, 0.01, 0.001],
    "kernel" : ["rbf", "sigmoid","poly"]
}
grid = GridSearchCV(SVR(),param_grid,refit=True, verbose=3)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV 1/5] END ......C=0.01, gamma=1, kernel=rbf;, score=-0.082 total time=   0.0s
[CV 2/5] END ......C=0.01, gamma=1, kernel=rbf;, score=-0.073 total time=   0.0s
[CV 3/5] END ......C=0.01, gamma=1, kernel=rbf;, score=-0.172 total time=   0.0s
[CV 4/5] END ......C=0.01, gamma=1, kernel=rbf;, score=-0.009 total time=   0.0s
[CV 5/5] END ......C=0.01, gamma=1, kernel=rbf;, score=-0.108 total time=   0.0s
[CV 1/5] END ..C=0.01, gamma=1, kernel=sigmoid;, score=-0.083 total time=   0.0s
[CV 2/5] END ..C=0.01, gamma=1, kernel=sigmoid;, score=-0.074 total time=   0.0s
[CV 3/5] END ..C=0.01, gamma=1, kernel=sigmoid;, score=-0.174 total time=   0.0s
[CV 4/5] END ..C=0.01, gamma=1, kernel=sigmoid;, score=-0.013 total time=   0.0s
[CV 5/5] END ..C=0.01, gamma=1, kernel=sigmoid;, score=-0.111 total time=   0.0s
[CV 1/5] END ......C=0.01, gamma=1, kernel=poly;, score=0.163 total time=   0.1s
[CV 2/5] END ......C=0.01, gamma=1, kernel=poly;, score=0.342 total time=   0.0s
[CV 3/5] END ......C=0.01, gamma=1, kernel=poly;, score=0.015 total time=   0.0s
[CV 4/5] END .....C=0.01, gamma=1, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END ......C=0.01, gamma=1, kernel=poly;, score=0.573 total time=   0.0s
[CV 1/5] END ....C=0.01, gamma=0.1, kernel=rbf;, score=-0.073 total time=   0.0s
[CV 2/5] END ....C=0.01, gamma=0.1, kernel=rbf;, score=-0.063 total time=   0.0s
[CV 3/5] END ....C=0.01, gamma=0.1, kernel=rbf;, score=-0.158 total time=   0.0s
[CV 4/5] END .....C=0.01, gamma=0.1, kernel=rbf;, score=0.004 total time=   0.0s
[CV 5/5] END ....C=0.01, gamma=0.1, kernel=rbf;, score=-0.092 total time=   0.0s
[CV 1/5] END C=0.01, gamma=0.1, kernel=sigmoid;, score=-0.087 total time=   0.0s
[CV 2/5] END C=0.01, gamma=0.1, kernel=sigmoid;, score=-0.078 total time=   0.0s
[CV 3/5] END C=0.01, gamma=0.1, kernel=sigmoid;, score=-0.180 total time=   0.0s
[CV 4/5] END C=0.01, gamma=0.1, kernel=sigmoid;, score=-0.019 total time=   0.0s
[CV 5/5] END C=0.01, gamma=0.1, kernel=sigmoid;, score=-0.116 total time=   0.0s
[CV 1/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.211 total time=   0.0s
[CV 2/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.462 total time=   0.0s
[CV 3/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.616 total time=   0.0s
[CV 4/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.271 total time=   0.0s
[CV 5/5] END ....C=0.01, gamma=0.1, kernel=poly;, score=0.434 total time=   0.0s
[CV 1/5] END ...C=0.01, gamma=0.01, kernel=rbf;, score=-0.080 total time=   0.0s
[CV 2/5] END ...C=0.01, gamma=0.01, kernel=rbf;, score=-0.069 total time=   0.0s
[CV 3/5] END ...C=0.01, gamma=0.01, kernel=rbf;, score=-0.168 total time=   0.0s
[CV 4/5] END ...C=0.01, gamma=0.01, kernel=rbf;, score=-0.007 total time=   0.0s
[CV 5/5] END ...C=0.01, gamma=0.01, kernel=rbf;, score=-0.105 total time=   0.0s
[CV 1/5] END C=0.01, gamma=0.01, kernel=sigmoid;, score=-0.082 total time=   0.0s
[CV 2/5] END C=0.01, gamma=0.01, kernel=sigmoid;, score=-0.071 total time=   0.0s
[CV 3/5] END C=0.01, gamma=0.01, kernel=sigmoid;, score=-0.171 total time=   0.0s
[CV 4/5] END C=0.01, gamma=0.01, kernel=sigmoid;, score=-0.010 total time=   0.0s
[CV 5/5] END C=0.01, gamma=0.01, kernel=sigmoid;, score=-0.108 total time=   0.0s
[CV 1/5] END ..C=0.01, gamma=0.01, kernel=poly;, score=-0.082 total time=   0.0s
[CV 2/5] END ..C=0.01, gamma=0.01, kernel=poly;, score=-0.072 total time=   0.0s
[CV 3/5] END ..C=0.01, gamma=0.01, kernel=poly;, score=-0.172 total time=   0.0s
[CV 4/5] END ..C=0.01, gamma=0.01, kernel=poly;, score=-0.011 total time=   0.0s
[CV 5/5] END ..C=0.01, gamma=0.01, kernel=poly;, score=-0.109 total time=   0.0s
[CV 1/5] END ..C=0.01, gamma=0.001, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 2/5] END ..C=0.01, gamma=0.001, kernel=rbf;, score=-0.073 total time=   0.0s
[CV 3/5] END ..C=0.01, gamma=0.001, kernel=rbf;, score=-0.173 total time=   0.0s
[CV 4/5] END ..C=0.01, gamma=0.001, kernel=rbf;, score=-0.013 total time=   0.0s
[CV 5/5] END ..C=0.01, gamma=0.001, kernel=rbf;, score=-0.110 total time=   0.0s
[CV 1/5] END C=0.01, gamma=0.001, kernel=sigmoid;, score=-0.083 total time=   0.0s
[CV 2/5] END C=0.01, gamma=0.001, kernel=sigmoid;, score=-0.074 total time=   0.0s
[CV 3/5] END C=0.01, gamma=0.001, kernel=sigmoid;, score=-0.174 total time=   0.0s
[CV 4/5] END C=0.01, gamma=0.001, kernel=sigmoid;, score=-0.013 total time=   0.0s
[CV 5/5] END C=0.01, gamma=0.001, kernel=sigmoid;, score=-0.111 total time=   0.0s
[CV 1/5] END .C=0.01, gamma=0.001, kernel=poly;, score=-0.083 total time=   0.0s
[CV 2/5] END .C=0.01, gamma=0.001, kernel=poly;, score=-0.074 total time=   0.0s
[CV 3/5] END .C=0.01, gamma=0.001, kernel=poly;, score=-0.174 total time=   0.0s
[CV 4/5] END .C=0.01, gamma=0.001, kernel=poly;, score=-0.013 total time=   0.0s
[CV 5/5] END .C=0.01, gamma=0.001, kernel=poly;, score=-0.111 total time=   0.0s
[CV 1/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.067 total time=   0.0s
[CV 2/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.058 total time=   0.0s
[CV 3/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.145 total time=   0.0s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.025 total time=   0.0s
[CV 5/5] END .......C=0.1, gamma=1, kernel=rbf;, score=-0.089 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=1, kernel=sigmoid;, score=-0.083 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=1, kernel=sigmoid;, score=-0.074 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=1, kernel=sigmoid;, score=-0.174 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=1, kernel=sigmoid;, score=-0.013 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=1, kernel=sigmoid;, score=-0.111 total time=   0.0s
[CV 1/5] END ......C=0.1, gamma=1, kernel=poly;, score=-0.043 total time=   0.2s
[CV 2/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.328 total time=   0.2s
[CV 3/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.113 total time=   0.2s
[CV 4/5] END ......C=0.1, gamma=1, kernel=poly;, score=-0.002 total time=   0.2s
[CV 5/5] END .......C=0.1, gamma=1, kernel=poly;, score=0.510 total time=   0.1s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.013 total time=   0.0s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.021 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=rbf;, score=-0.010 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.124 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.050 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=0.1, kernel=sigmoid;, score=-0.120 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=0.1, kernel=sigmoid;, score=-0.124 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=0.1, kernel=sigmoid;, score=-0.234 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=0.1, kernel=sigmoid;, score=-0.067 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=0.1, kernel=sigmoid;, score=-0.168 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.245 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.477 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.634 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.207 total time=   0.0s
[CV 5/5] END .....C=0.1, gamma=0.1, kernel=poly;, score=0.512 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.053 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.028 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.108 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.040 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=0.01, kernel=rbf;, score=-0.058 total time=   0.0s
[CV 1/5] END C=0.1, gamma=0.01, kernel=sigmoid;, score=-0.069 total time=   0.0s
[CV 2/5] END C=0.1, gamma=0.01, kernel=sigmoid;, score=-0.050 total time=   0.0s
[CV 3/5] END C=0.1, gamma=0.01, kernel=sigmoid;, score=-0.141 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=0.01, kernel=sigmoid;, score=0.014 total time=   0.0s
[CV 5/5] END C=0.1, gamma=0.01, kernel=sigmoid;, score=-0.084 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.01, kernel=poly;, score=-0.073 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.01, kernel=poly;, score=-0.051 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.01, kernel=poly;, score=-0.149 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=0.01, kernel=poly;, score=0.005 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.01, kernel=poly;, score=-0.093 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.080 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.068 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.167 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.006 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=rbf;, score=-0.105 total time=   0.0s
[CV 1/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=-0.081 total time=   0.0s
[CV 2/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=-0.071 total time=   0.0s
[CV 3/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=-0.170 total time=   0.0s
[CV 4/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=-0.010 total time=   0.0s
[CV 5/5] END C=0.1, gamma=0.001, kernel=sigmoid;, score=-0.108 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.083 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.074 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.174 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.013 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=0.001, kernel=poly;, score=-0.111 total time=   0.0s
[CV 1/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.018 total time=   0.0s
[CV 2/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.051 total time=   0.0s
[CV 3/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.080 total time=   0.0s
[CV 4/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.166 total time=   0.0s
[CV 5/5] END ..........C=1, gamma=1, kernel=rbf;, score=0.081 total time=   0.0s
[CV 1/5] END .....C=1, gamma=1, kernel=sigmoid;, score=-0.083 total time=   0.0s
[CV 2/5] END .....C=1, gamma=1, kernel=sigmoid;, score=-0.074 total time=   0.0s
[CV 3/5] END .....C=1, gamma=1, kernel=sigmoid;, score=-0.174 total time=   0.0s
[CV 4/5] END .....C=1, gamma=1, kernel=sigmoid;, score=-0.013 total time=   0.0s
[CV 5/5] END .....C=1, gamma=1, kernel=sigmoid;, score=-0.111 total time=   0.0s
[CV 1/5] END .........C=1, gamma=1, kernel=poly;, score=0.007 total time=  11.0s
[CV 2/5] END .........C=1, gamma=1, kernel=poly;, score=0.480 total time=   1.4s
[CV 3/5] END .........C=1, gamma=1, kernel=poly;, score=0.640 total time=   0.9s
[CV 4/5] END .........C=1, gamma=1, kernel=poly;, score=0.257 total time=   3.2s
[CV 5/5] END .........C=1, gamma=1, kernel=poly;, score=0.385 total time=   2.3s
[CV 1/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.189 total time=   0.0s
[CV 2/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.254 total time=   0.0s
[CV 3/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.533 total time=   0.0s
[CV 4/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.347 total time=   0.0s
[CV 5/5] END ........C=1, gamma=0.1, kernel=rbf;, score=0.503 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-0.522 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-0.657 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-0.901 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-0.760 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.1, kernel=sigmoid;, score=-0.761 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.229 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.467 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.543 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.034 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.1, kernel=poly;, score=0.544 total time=   0.0s
[CV 1/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.121 total time=   0.0s
[CV 2/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.221 total time=   0.0s
[CV 3/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.269 total time=   0.0s
[CV 4/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.305 total time=   0.0s
[CV 5/5] END .......C=1, gamma=0.01, kernel=rbf;, score=0.252 total time=   0.0s
[CV 1/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.042 total time=   0.0s
[CV 2/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.131 total time=   0.0s
[CV 3/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.107 total time=   0.0s
[CV 4/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.203 total time=   0.0s
[CV 5/5] END ...C=1, gamma=0.01, kernel=sigmoid;, score=0.112 total time=   0.0s
[CV 1/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.013 total time=   0.0s
[CV 2/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.131 total time=   0.0s
[CV 3/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.063 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.134 total time=   0.0s
[CV 5/5] END ......C=1, gamma=0.01, kernel=poly;, score=0.049 total time=   0.0s
[CV 1/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.014 total time=   0.0s
[CV 3/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.096 total time=   0.0s
[CV 4/5] END ......C=1, gamma=0.001, kernel=rbf;, score=0.050 total time=   0.0s
[CV 5/5] END .....C=1, gamma=0.001, kernel=rbf;, score=-0.051 total time=   0.0s
[CV 1/5] END .C=1, gamma=0.001, kernel=sigmoid;, score=-0.066 total time=   0.0s
[CV 2/5] END .C=1, gamma=0.001, kernel=sigmoid;, score=-0.044 total time=   0.0s
[CV 3/5] END .C=1, gamma=0.001, kernel=sigmoid;, score=-0.134 total time=   0.0s
[CV 4/5] END ..C=1, gamma=0.001, kernel=sigmoid;, score=0.019 total time=   0.0s
[CV 5/5] END .C=1, gamma=0.001, kernel=sigmoid;, score=-0.079 total time=   0.0s
[CV 1/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.083 total time=   0.0s
[CV 2/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.074 total time=   0.0s
[CV 3/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.174 total time=   0.0s
[CV 4/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.013 total time=   0.0s
[CV 5/5] END ....C=1, gamma=0.001, kernel=poly;, score=-0.111 total time=   0.0s
[CV 1/5] END .........C=10, gamma=1, kernel=rbf;, score=0.166 total time=   0.0s
[CV 2/5] END .........C=10, gamma=1, kernel=rbf;, score=0.231 total time=   0.0s
[CV 3/5] END .........C=10, gamma=1, kernel=rbf;, score=0.468 total time=   0.0s
[CV 4/5] END .........C=10, gamma=1, kernel=rbf;, score=0.212 total time=   0.0s
[CV 5/5] END .........C=10, gamma=1, kernel=rbf;, score=0.377 total time=   0.0s
[CV 1/5] END ....C=10, gamma=1, kernel=sigmoid;, score=-0.084 total time=   0.0s
[CV 2/5] END ....C=10, gamma=1, kernel=sigmoid;, score=-0.077 total time=   0.0s
[CV 3/5] END ....C=10, gamma=1, kernel=sigmoid;, score=-0.175 total time=   0.0s
[CV 4/5] END ....C=10, gamma=1, kernel=sigmoid;, score=-0.015 total time=   0.0s
[CV 5/5] END ....C=10, gamma=1, kernel=sigmoid;, score=-0.111 total time=   0.0s
[CV 1/5] END .......C=10, gamma=1, kernel=poly;, score=-0.019 total time=  43.0s
[CV 2/5] END .......C=10, gamma=1, kernel=poly;, score=-0.808 total time=  10.7s
[CV 3/5] END .......C=10, gamma=1, kernel=poly;, score=-0.152 total time=   7.2s
[CV 4/5] END .......C=10, gamma=1, kernel=poly;, score=-0.335 total time=  26.9s
[CV 5/5] END ........C=10, gamma=1, kernel=poly;, score=0.163 total time=  26.0s
[CV 1/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.156 total time=   0.0s
[CV 2/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.433 total time=   0.0s
[CV 3/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.706 total time=   0.0s
[CV 4/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.395 total time=   0.0s
[CV 5/5] END .......C=10, gamma=0.1, kernel=rbf;, score=0.541 total time=   0.0s
[CV 1/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-19.954 total time=   0.0s
[CV 2/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-21.311 total time=   0.0s
[CV 3/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-28.554 total time=   0.0s
[CV 4/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-29.648 total time=   0.0s
[CV 5/5] END .C=10, gamma=0.1, kernel=sigmoid;, score=-25.433 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.163 total time=   0.1s
[CV 2/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.342 total time=   0.1s
[CV 3/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.015 total time=   0.1s
[CV 4/5] END .....C=10, gamma=0.1, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.1, kernel=poly;, score=0.573 total time=   0.0s
[CV 1/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.204 total time=   0.0s
[CV 2/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.474 total time=   0.0s
[CV 3/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.701 total time=   0.0s
[CV 4/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.432 total time=   0.0s
[CV 5/5] END ......C=10, gamma=0.01, kernel=rbf;, score=0.592 total time=   0.0s
[CV 1/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.199 total time=   0.0s
[CV 2/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.465 total time=   0.0s
[CV 3/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.685 total time=   0.0s
[CV 4/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.447 total time=   0.0s
[CV 5/5] END ..C=10, gamma=0.01, kernel=sigmoid;, score=0.583 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.211 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.462 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.616 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.271 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.01, kernel=poly;, score=0.434 total time=   0.0s
[CV 1/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.144 total time=   0.0s
[CV 2/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.277 total time=   0.0s
[CV 3/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.338 total time=   0.0s
[CV 4/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.342 total time=   0.0s
[CV 5/5] END .....C=10, gamma=0.001, kernel=rbf;, score=0.283 total time=   0.0s
[CV 1/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.062 total time=   0.0s
[CV 2/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.174 total time=   0.0s
[CV 3/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.161 total time=   0.0s
[CV 4/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.233 total time=   0.0s
[CV 5/5] END .C=10, gamma=0.001, kernel=sigmoid;, score=0.151 total time=   0.0s
[CV 1/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.082 total time=   0.0s
[CV 2/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.072 total time=   0.0s
[CV 3/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.172 total time=   0.0s
[CV 4/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.011 total time=   0.0s
[CV 5/5] END ...C=10, gamma=0.001, kernel=poly;, score=-0.109 total time=   0.0s

GridSearchCV(estimator=SVR(),
             param_grid={'C': [0.01, 0.1, 1, 10],
                         'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'sigmoid', 'poly']},
             verbose=3)

In [17]:
grid.best_params_

{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}

In [18]:
grid_prediction= grid.predict(X_test)
print("r2 score", r2_score(y_test, grid_prediction))
print("mae", mean_absolute_error(y_test, grid_prediction))

r2 score 0.5031578656078388
mae 3.8997508899462017